In [2]:
# Data manipulation
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Display all columns
pd.set_option("display.max_columns", None)

# Better looking plots
plt.style.use("ggplot")

In [8]:
import pandas as pd

df = pd.read_csv(r"D:\Machine Learning\Machine Learning\Internship\Day 4 Production-Grade Regression\data\raw\Travel details dataset.csv")
print(df.head())

   Trip ID       Destination Start date   End date  Duration (days)  \
0        1        London, UK   5/1/2023   5/8/2023                7
1        2  Phuket, Thailand  6/15/2023  6/20/2023                5
2        3   Bali, Indonesia   7/1/2023   7/8/2023                7
3        4     New York, USA  8/15/2023  8/29/2023               14
4        5      Tokyo, Japan  9/10/2023  9/17/2023                7

   Traveler name  Traveler age Traveler gender Traveler nationality  \
0     John Smith            35            Male             American
1       Jane Doe            28          Female             Canadian
2      David Lee            45            Male               Korean
3  Sarah Johnson            29          Female              British
4     Kim Nguyen            26          Female           Vietnamese

  Accommodation type Accommodation cost Transportation type  \
0              Hotel               1200              Flight
1             Resort                800              Flight
2              Villa               1000              Flight
3              Hotel               2000              Flight
4             Airbnb                700               Train

  Transportation cost
0                 600
1                 500
2                 700
3                1000
4                 200

In [9]:
print(df.tail())

    Trip ID Destination  Start date    End date  Duration (days)  \
25       26      Hawaii    8/1/2023   8/10/2023                9
26       27   Barcelona  10/20/2023  10/28/2023                8
27       28       Japan   5/10/2022   5/18/2022                8
28       29    Thailand   6/15/2022   6/22/2022                7
29       30      France    7/2/2022   7/11/2022                9

   Traveler name  Traveler age Traveler gender Traveler nationality  \
25     David Kim            34            Male               Korean
26  Maria Garcia            31          Female              Spanish
27   Alice Smith            30          Female             American
28   Bob Johnson            45            Male             Canadian
29   Charlie Lee            25            Male               Korean

   Accommodation type Accommodation cost Transportation type  \
25             Resort            $2,000                Plane
26              Hotel            $1,100                Train
27              Hotel              $800                Plane
28             Hostel              $200                Train
29             Airbnb              $600           Car rental

   Transportation cost
25               $800
26               $150
27               $500
28               $150
29                $300

In [10]:
print(df.sample(5, random_state=42))

    Trip ID             Destination Start date   End date  Duration (days)  \
27       28                   Japan  5/10/2022  5/18/2022                8
15       16     Edinburgh, Scotland   9/5/2024  9/12/2024                7
23       24                 Bangkok  9/15/2023  9/23/2023                8
17       18                    Bali  8/15/2023  8/25/2023               10
8         9  Amsterdam, Netherlands  2/14/2024  2/21/2024                7

      Traveler name  Traveler age Traveler gender Traveler nationality  \
27      Alice Smith            30          Female             American
15  James MacKenzie            32            Male             Scottish
23        Raj Patel            40            Male               Indian
17    Michael Chang            28            Male              Chinese
8     Laura Janssen            31          Female                Dutch

   Accommodation type Accommodation cost Transportation type  \
27              Hotel              $800                Plane
15              Hotel                900               Train
23             Hostel              $400                Plane
17             Resort            $1,500                Plane
8               Hotel               1200               Train

   Transportation cost
27               $500
15                 150
23               $500
17               $700
8                  200

In [11]:
df.columns

Index(['Trip ID', 'Destination', 'Start date', 'End date', 'Duration (days)',
       'Traveler name', 'Traveler age', 'Traveler gender',
       'Traveler nationality', 'Accommodation type', 'Accommodation cost',
       'Transportation type', 'Transportation cost'],
      dtype='str')

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Trip ID               30 non-null     int64
 1   Destination           30 non-null     str
 2   Start date            30 non-null     str
 3   End date              30 non-null     str
 4   Duration (days)       30 non-null     int64
 5   Traveler name         30 non-null     str
 6   Traveler age          30 non-null     int64
 7   Traveler gender       30 non-null     str
 8   Traveler nationality  30 non-null     str
 9   Accommodation type    30 non-null     str
 10  Accommodation cost    30 non-null     str
 11  Transportation type   30 non-null     str
 12  Transportation cost   30 non-null     str
dtypes: int64(3), str(10)
memory usage: 3.2 KB

In [13]:
df.describe()

         Trip ID  Duration (days)  Traveler age
count  30.000000        30.000000     30.000000
mean   15.500000         7.666667     32.866667
std     8.803408         1.825742      6.811417
min     1.000000         5.000000     24.000000
25%     8.250000         7.000000     28.000000
50%    15.500000         7.000000     31.000000
75%    22.750000         8.750000     35.750000
max    30.000000        14.000000     48.000000

In [14]:
df.describe(include="all")

,Trip ID,Destination,Start date,End date,Duration (days),Traveler name,Traveler age,Traveler gender,Traveler nationality,Accommodation type,Accommodation cost,Transportation type,Transportation cost
count,30.000000,30,30,30,30.000000,30,30.000000,30,30,30,30,30,30
unique,NaN,29,27,30,NaN,29,NaN,2,18,6,24,5,19
top,NaN,Paris,8/15/2023,5/8/2023,NaN,Sarah Johnson,NaN,Male,American,Hotel,1200,Flight,$150
freq,NaN,2,2,1,NaN,2,NaN,15,5,14,2,12,3
mean,15.500000,NaN,NaN,NaN,7.666667,NaN,32.866667,NaN,NaN,NaN,NaN,NaN,NaN
std,8.803408,NaN,NaN,NaN,1.825742,NaN,6.811417,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,NaN,NaN,NaN,5.000000,NaN,24.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,8.250000,NaN,NaN,NaN,7.000000,NaN,28.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,15.500000,NaN,NaN,NaN,7.000000,NaN,31.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,22.750000,NaN,NaN,NaN,8.750000,NaN,35.750000,NaN,NaN,NaN,NaN,NaN,NaN
max,30.000000,NaN,NaN,NaN,14.000000,NaN,48.000000,NaN,NaN,NaN,NaN,NaN,NaN