In [14]:
import os
import joblib
import pandas as pd
import numpy as np

In [ ]:

# TASK 1 — FIND KMEANS MODEL


base_path = r"D:\AI-Lab-99"

model_path = None

for root, dirs, files in os.walk(base_path):
    for file in files:
        
        if file.lower() == "kmeans_model.pkl":
            model_path = os.path.join(root, file)
            break
    
    if model_path is not None:
        break


if model_path is not None:
    print(" K-Means model found!")
    print("Model path:")
    print(model_path)
else:
    print(" kmeans_model.pkl not found.")

✅ K-Means model found!
Model path:
D:\AI-Lab-99\Week 4\Module 6 Customer Segmentation Model Development\kmeans_model.pkl

In [ ]:

# LOAD SAVED KMEANS MODEL


kmeans_model = joblib.load(model_path)

print(" K-Means model loaded successfully.")
print("Model type:", type(kmeans_model).__name__)

✅ K-Means model loaded successfully.
Model type: KMeans

In [ ]:

# MODEL INFORMATION


print("Model Type:", type(kmeans_model).__name__)

if hasattr(kmeans_model, "n_clusters"):
    print("Number of Clusters:", kmeans_model.n_clusters)

if hasattr(kmeans_model, "n_features_in_"):
    print("Number of Input Features:", kmeans_model.n_features_in_)

if hasattr(kmeans_model, "cluster_centers_"):
    print("Cluster Centers Shape:", kmeans_model.cluster_centers_.shape)

Model Type: KMeans
Number of Clusters: 2
Number of Input Features: 40
Cluster Centers Shape: (2, 40)

In [ ]:

# TASK 2 — FIND PREPROCESSING / SCALER FILES


preprocessing_files = []

for root, dirs, files in os.walk(base_path):
    for file in files:

        file_lower = file.lower()

        if (
            file_lower.endswith(".pkl")
            or file_lower.endswith(".joblib")
        ):

            if file_lower != "kmeans_model.pkl":
                preprocessing_files.append(
                    os.path.join(root, file)
                )


print("Possible preprocessing/model files:")

if preprocessing_files:

    for path in preprocessing_files:
        print("", path)

else:
    print(" No additional .pkl/.joblib files found.")

Possible preprocessing/model files:
📁 D:\AI-Lab-99\3_Titanic_preprocessing\preprocessing_pipeline.joblib
📁 D:\AI-Lab-99\House Price\best_model.pkl
📁 D:\AI-Lab-99\House Price\model_columns.pkl
📁 D:\AI-Lab-99\Week 4\Module 6 Customer Segmentation Model Development\feature_list.pkl
📁 D:\AI-Lab-99\Week 4\Module 6 Customer Segmentation Model Development\standard_scaler.pkl

In [ ]:
# =====================================================
# FIND FINAL DATASET AUTOMATICALLY
# =====================================================

dataset_files = []

for root, dirs, files in os.walk(base_path):
    for file in files:

        if file.lower().endswith(".csv"):

            if "final" in file.lower():
                dataset_files.append(
                    os.path.join(root, file)
                )


print("Final dataset candidates:")

if dataset_files:

    for path in dataset_files:
        print("", path)

else:
    print(" Final dataset not found.")

Final dataset candidates:
📊 D:\AI-Lab-99\Week 3\Module 5 Feature Engineering & Data Preprocessing\Customer_Personality_Final_Dataset.csv
📊 D:\AI-Lab-99\Week 4\Module 6 Customer Segmentation Model Development\Customer_Segmentation_Final.csv
📊 D:\AI-Lab-99\Week 4\Module 6 Customer Segmentation Model Development\Final_Model_Selection.csv
📊 D:\AI-Lab-99\Week 4\Module 7 Cluster Evaluation & Customer Profiling\Customer_Segmentation_Final.csv
📊 D:\AI-Lab-99\Week 4\Module 7 Cluster Evaluation & Customer Profiling\Final_Customer_Profile_Report.csv
📊 D:\AI-Lab-99\Week 5\Day 1\Final Dataset.csv

In [ ]:
# =====================================================
# FIND FINAL DATASET AUTOMATICALLY
# =====================================================

dataset_files = []

for root, dirs, files in os.walk(base_path):
    for file in files:

        if file.lower().endswith(".csv"):

            if "final" in file.lower():
                dataset_files.append(
                    os.path.join(root, file)
                )


print("Final dataset candidates:")

if dataset_files:

    for path in dataset_files:
        print("", path)

else:
    print(" Final dataset not found.")

Final dataset candidates:
📊 D:\AI-Lab-99\Week 3\Module 5 Feature Engineering & Data Preprocessing\Customer_Personality_Final_Dataset.csv
📊 D:\AI-Lab-99\Week 4\Module 6 Customer Segmentation Model Development\Customer_Segmentation_Final.csv
📊 D:\AI-Lab-99\Week 4\Module 6 Customer Segmentation Model Development\Final_Model_Selection.csv
📊 D:\AI-Lab-99\Week 4\Module 7 Cluster Evaluation & Customer Profiling\Customer_Segmentation_Final.csv
📊 D:\AI-Lab-99\Week 4\Module 7 Cluster Evaluation & Customer Profiling\Final_Customer_Profile_Report.csv
📊 D:\AI-Lab-99\Week 5\Day 1\Final Dataset.csv

In [ ]:
# =====================================================
# LOAD FINAL DATASET
# =====================================================

if dataset_files:

    dataset_path = dataset_files[0]

    df = pd.read_csv(dataset_path)

    print(" Final dataset loaded successfully.")
    print("Dataset path:")
    print(dataset_path)

    print("\nShape:")
    print(df.shape)

else:

    print(" Dataset could not be found.")

✅ Final dataset loaded successfully.
Dataset path:
D:\AI-Lab-99\Week 3\Module 5 Feature Engineering & Data Preprocessing\Customer_Personality_Final_Dataset.csv

Shape:
(2038, 40)

In [22]:
# =====================================================
# CHECK FINAL DATASET
# =====================================================

print("Number of columns:", len(df.columns))

print("\nColumns:")
for i, column in enumerate(df.columns, start=1):
    print(i, "→", column)

Number of columns: 40

Columns:
1 → Education
2 → Marital_Status
3 → Income
4 → Recency
5 → MntWines
6 → MntFruits
7 → MntMeatProducts
8 → MntFishProducts
9 → MntSweetProducts
10 → MntGoldProds
11 → NumDealsPurchases
12 → NumWebPurchases
13 → NumCatalogPurchases
14 → NumStorePurchases
15 → NumWebVisitsMonth
16 → AcceptedCmp3
17 → AcceptedCmp4
18 → AcceptedCmp5
19 → AcceptedCmp1
20 → AcceptedCmp2
21 → Complain
22 → Response
23 → Age
24 → Year
25 → Month
26 → Day
27 → Customer_Age
28 → Customer_Tenure
29 → Total_Children
30 → Partner
31 → Family_size
32 → Total_spending
33 → Total_Purchase
34 → Total_Campaign
35 → Average Spending per Purchase
36 → Digital_Engagement
37 → Deal_Dependency
38 → Preferred_Shopping_Channel
39 → Product_Preference
40 → Customer_Activity_Level

In [ ]:

# CHECK EXISTING SEGMENT COLUMNS


possible_segment_columns = [
    "Cluster",
    "cluster",
    "Customer_Segment",
    "Customer Segment"
]

print("Checking segment columns...\n")

for column in possible_segment_columns:

    if column in df.columns:

        print(f" Found: {column}")

        print("\nUnique values:")
        print(df[column].unique())

        print("\nValue counts:")
        print(df[column].value_counts())

Checking segment columns...

In [24]:
# =====================================================
# TASK 3 — IDENTIFY MODEL INPUT
# =====================================================

print("K-Means model information")
print("=" * 50)

print("Model type:", type(kmeans_model).__name__)

if hasattr(kmeans_model, "n_features_in_"):
    print("Expected number of features:", kmeans_model.n_features_in_)

if hasattr(kmeans_model, "cluster_centers_"):
    print("Cluster centers shape:", kmeans_model.cluster_centers_.shape)

print("\nModel parameters:")
print(kmeans_model.get_params())

K-Means model information
==================================================
Model type: KMeans
Expected number of features: 40
Cluster centers shape: (2, 40)

Model parameters:
{'algorithm': 'lloyd', 'copy_x': True, 'init': 'k-means++', 'max_iter': 300, 'n_clusters': 2, 'n_init': 10, 'random_state': 42, 'tol': 0.0001, 'verbose': 0}

In [ ]:

# CHECK FOR PIPELINE / PREPROCESSOR


print("Checking model structure...\n")

print("Model class:")
print(type(kmeans_model))

print("\nModel attributes related to preprocessing:")

for attr in dir(kmeans_model):

    if any(word in attr.lower() for word in [
        "scale",
        "transform",
        "feature",
        "preprocess",
        "pipeline"
    ]):
        print("→", attr)

Checking model structure...

Model class:
<class 'sklearn.cluster._kmeans.KMeans'>

Model attributes related to preprocessing:
→ _n_features_out
→ _transform
→ feature_names_in_
→ fit_transform
→ get_feature_names_out
→ n_features_in_
→ transform

In [ ]:

# DATASET FEATURE INSPECTION


print("Dataset shape:", df.shape)

print("\nAll dataset columns:\n")

for i, col in enumerate(df.columns, start=1):
    print(f"{i:02d}. {col}")

Dataset shape: (2038, 40)

All dataset columns:

01. Education
02. Marital_Status
03. Income
04. Recency
05. MntWines
06. MntFruits
07. MntMeatProducts
08. MntFishProducts
09. MntSweetProducts
10. MntGoldProds
11. NumDealsPurchases
12. NumWebPurchases
13. NumCatalogPurchases
14. NumStorePurchases
15. NumWebVisitsMonth
16. AcceptedCmp3
17. AcceptedCmp4
18. AcceptedCmp5
19. AcceptedCmp1
20. AcceptedCmp2
21. Complain
22. Response
23. Age
24. Year
25. Month
26. Day
27. Customer_Age
28. Customer_Tenure
29. Total_Children
30. Partner
31. Family_size
32. Total_spending
33. Total_Purchase
34. Total_Campaign
35. Average Spending per Purchase
36. Digital_Engagement
37. Deal_Dependency
38. Preferred_Shopping_Channel
39. Product_Preference
40. Customer_Activity_Level

In [27]:
# =====================================================
# REMOVE EXISTING SEGMENT LABELS
# =====================================================

segment_columns = [
    "Cluster",
    "cluster",
    "Customer_Segment",
    "Customer Segment"
]

feature_candidates = [
    col for col in df.columns
    if col not in segment_columns
]

print("Possible input features:")
print("=" * 50)

for i, col in enumerate(feature_candidates, start=1):
    print(f"{i:02d}. {col}")

print("\nTotal possible features:", len(feature_candidates))

Possible input features:
==================================================
01. Education
02. Marital_Status
03. Income
04. Recency
05. MntWines
06. MntFruits
07. MntMeatProducts
08. MntFishProducts
09. MntSweetProducts
10. MntGoldProds
11. NumDealsPurchases
12. NumWebPurchases
13. NumCatalogPurchases
14. NumStorePurchases
15. NumWebVisitsMonth
16. AcceptedCmp3
17. AcceptedCmp4
18. AcceptedCmp5
19. AcceptedCmp1
20. AcceptedCmp2
21. Complain
22. Response
23. Age
24. Year
25. Month
26. Day
27. Customer_Age
28. Customer_Tenure
29. Total_Children
30. Partner
31. Family_size
32. Total_spending
33. Total_Purchase
34. Total_Campaign
35. Average Spending per Purchase
36. Digital_Engagement
37. Deal_Dependency
38. Preferred_Shopping_Channel
39. Product_Preference
40. Customer_Activity_Level

Total possible features: 40

In [28]:
# =====================================================
# NUMERIC FEATURE INSPECTION
# =====================================================

numeric_features = df[feature_candidates].select_dtypes(
    include=np.number
).columns.tolist()

print("Numeric features:")
print("=" * 50)

for i, col in enumerate(numeric_features, start=1):
    print(f"{i:02d}. {col}")

print("\nTotal numeric features:", len(numeric_features))

Numeric features:
==================================================
01. Education
02. Marital_Status
03. Income
04. Recency
05. MntWines
06. MntFruits
07. MntMeatProducts
08. MntFishProducts
09. MntSweetProducts
10. MntGoldProds
11. NumDealsPurchases
12. NumWebPurchases
13. NumCatalogPurchases
14. NumStorePurchases
15. NumWebVisitsMonth
16. AcceptedCmp3
17. AcceptedCmp4
18. AcceptedCmp5
19. AcceptedCmp1
20. AcceptedCmp2
21. Complain
22. Response
23. Age
24. Year
25. Month
26. Day
27. Customer_Age
28. Customer_Tenure
29. Total_Children
30. Partner
31. Family_size
32. Total_spending
33. Total_Purchase
34. Total_Campaign
35. Average Spending per Purchase
36. Digital_Engagement
37. Deal_Dependency
38. Preferred_Shopping_Channel
39. Product_Preference
40. Customer_Activity_Level

Total numeric features: 40

In [ ]:

# TASK 3 — CHECK STORED FEATURE NAMES


print("Checking whether feature names were saved with the model...")
print("=" * 60)

possible_attributes = [
    "feature_names_in_",
    "feature_names",
    "features",
    "input_features"
]

found = False

for attr in possible_attributes:

    if hasattr(kmeans_model, attr):

        value = getattr(kmeans_model, attr)

        print(f"\n Found: {attr}")
        print(value)

        found = True

if not found:

    print("\n Feature names are not directly stored in K-Means model.")

Checking whether feature names were saved with the model...
============================================================

✅ Found: feature_names_in_
['Education' 'Marital_Status' 'Income' 'Recency' 'MntWines' 'MntFruits'
 'MntMeatProducts' 'MntFishProducts' 'MntSweetProducts' 'MntGoldProds'
 'NumDealsPurchases' 'NumWebPurchases' 'NumCatalogPurchases'
 'NumStorePurchases' 'NumWebVisitsMonth' 'AcceptedCmp3' 'AcceptedCmp4'
 'AcceptedCmp5' 'AcceptedCmp1' 'AcceptedCmp2' 'Complain' 'Response' 'Age'
 'Year' 'Month' 'Day' 'Customer_Age' 'Customer_Tenure' 'Total_Children'
 'Partner' 'Family_size' 'Total_spending' 'Total_Purchase'
 'Total_Campaign' 'Average Spending per Purchase' 'Digital_Engagement'
 'Deal_Dependency' 'Preferred_Shopping_Channel' 'Product_Preference'
 'Customer_Activity_Level']

In [ ]:
# =====================================================
# INSPECT PREPROCESSING FILES
# =====================================================

if preprocessing_files:

    print("Inspecting saved preprocessing files")
    print("=" * 60)

    for path in preprocessing_files:

        print("\nFile:")
        print(path)

        try:

            obj = joblib.load(path)

            print("Object type:", type(obj).__name__)

            if hasattr(obj, "feature_names_in_"):

                print(
                    "Feature names:"
                )

                print(
                    obj.feature_names_in_
                )

            if hasattr(obj, "n_features_in_"):

                print(
                    "Number of input features:",
                    obj.n_features_in_
                )

        except Exception as e:

            print("Could not inspect:", e)

else:

    print(" No additional preprocessing file found.")

Inspecting saved preprocessing files
============================================================

File:
D:\AI-Lab-99\3_Titanic_preprocessing\preprocessing_pipeline.joblib
Object type: ColumnTransformer
Feature names:
['age' 'fare' 'sibsp' 'parch' 'sex' 'embarked' 'pclass']
Number of input features: 7

File:
D:\AI-Lab-99\House Price\best_model.pkl
Object type: XGBRegressor
Feature names:
['Id' 'MSSubClass' 'LotFrontage' 'LotArea' 'OverallQual' 'OverallCond'
 'YearBuilt' 'YearRemodAdd' 'MasVnrArea' 'BsmtFinSF1' 'BsmtFinSF2'
 'BsmtUnfSF' 'TotalBsmtSF' '1stFlrSF' '2ndFlrSF' 'LowQualFinSF'
 'GrLivArea' 'BsmtFullBath' 'BsmtHalfBath' 'FullBath' 'HalfBath'
 'BedroomAbvGr' 'KitchenAbvGr' 'TotRmsAbvGrd' 'Fireplaces' 'GarageYrBlt'
 'GarageCars' 'GarageArea' 'WoodDeckSF' 'OpenPorchSF' 'EnclosedPorch'
 '3SsnPorch' 'ScreenPorch' 'PoolArea' 'MiscVal' 'MoSold' 'YrSold'
 'MSZoning_C (all)' 'MSZoning_FV' 'MSZoning_RH' 'MSZoning_RL'
 'MSZoning_RM' 'Street_Grvl' 'Street_Pave' 'LotShape_IR1' 'LotShape_IR2'
 'LotShape_IR3' 'LotShape_Reg' 'LandContour_Bnk' 'LandContour_HLS'
 'LandContour_Low' 'LandContour_Lvl' 'Utilities_AllPub' 'Utilities_NoSeWa'
 'LotConfig_Corner' 'LotConfig_CulDSac' 'LotConfig_FR2' 'LotConfig_FR3'
 'LotConfig_Inside' 'LandSlope_Gtl' 'LandSlope_Mod' 'LandSlope_Sev'
 'Neighborhood_Blmngtn' 'Neighborhood_Blueste' 'Neighborhood_BrDale'
 'Neighborhood_BrkSide' 'Neighborhood_ClearCr' 'Neighborhood_CollgCr'
 'Neighborhood_Crawfor' 'Neighborhood_Edwards' 'Neighborhood_Gilbert'
 'Neighborhood_IDOTRR' 'Neighborhood_MeadowV' 'Neighborhood_Mitchel'
 'Neighborhood_NAmes' 'Neighborhood_NPkVill' 'Neighborhood_NWAmes'
 'Neighborhood_NoRidge' 'Neighborhood_NridgHt' 'Neighborhood_OldTown'
 'Neighborhood_SWISU' 'Neighborhood_Sawyer' 'Neighborhood_SawyerW'
 'Neighborhood_Somerst' 'Neighborhood_StoneBr' 'Neighborhood_Timber'
 'Neighborhood_Veenker' 'Condition1_Artery' 'Condition1_Feedr'
 'Condition1_Norm' 'Condition1_PosA' 'Condition1_PosN' 'Condition1_RRAe'
 'Condition1_RRAn' 'Condition1_RRNe' 'Condition1_RRNn' 'Condition2_Artery'
 'Condition2_Feedr' 'Condition2_Norm' 'Condition2_PosA' 'Condition2_PosN'
 'Condition2_RRAe' 'Condition2_RRAn' 'Condition2_RRNn' 'BldgType_1Fam'
 'BldgType_2fmCon' 'BldgType_Duplex' 'BldgType_Twnhs' 'BldgType_TwnhsE'
 'HouseStyle_1.5Fin' 'HouseStyle_1.5Unf' 'HouseStyle_1Story'
 'HouseStyle_2.5Fin' 'HouseStyle_2.5Unf' 'HouseStyle_2Story'
 'HouseStyle_SFoyer' 'HouseStyle_SLvl' 'RoofStyle_Flat' 'RoofStyle_Gable'
 'RoofStyle_Gambrel' 'RoofStyle_Hip' 'RoofStyle_Mansard' 'RoofStyle_Shed'
 'RoofMatl_ClyTile' 'RoofMatl_CompShg' 'RoofMatl_Membran' 'RoofMatl_Metal'
 'RoofMatl_Roll' 'RoofMatl_Tar&Grv' 'RoofMatl_WdShake' 'RoofMatl_WdShngl'
 'Exterior1st_AsbShng' 'Exterior1st_AsphShn' 'Exterior1st_BrkComm'
 'Exterior1st_BrkFace' 'Exterior1st_CBlock' 'Exterior1st_CemntBd'
 'Exterior1st_HdBoard' 'Exterior1st_ImStucc' 'Exterior1st_MetalSd'
 'Exterior1st_Plywood' 'Exterior1st_Stone' 'Exterior1st_Stucco'
 'Exterior1st_VinylSd' 'Exterior1st_Wd Sdng' 'Exterior1st_WdShing'
 'Exterior2nd_AsbShng' 'Exterior2nd_AsphShn' 'Exterior2nd_Brk Cmn'
 'Exterior2nd_BrkFace' 'Exterior2nd_CBlock' 'Exterior2nd_CmentBd'
 'Exterior2nd_HdBoard' 'Exterior2nd_ImStucc' 'Exterior2nd_MetalSd'
 'Exterior2nd_Other' 'Exterior2nd_Plywood' 'Exterior2nd_Stone'
 'Exterior2nd_Stucco' 'Exterior2nd_VinylSd' 'Exterior2nd_Wd Sdng'
 'Exterior2nd_Wd Shng' 'ExterQual_Ex' 'ExterQual_Fa' 'ExterQual_Gd'
 'ExterQual_TA' 'ExterCond_Ex' 'ExterCond_Fa' 'ExterCond_Gd'
 'ExterCond_Po' 'ExterCond_TA' 'Foundation_BrkTil' 'Foundation_CBlock'
 'Foundation_PConc' 'Foundation_Slab' 'Foundation_Stone' 'Foundation_Wood'
 'BsmtQual_Ex' 'BsmtQual_Fa' 'BsmtQual_Gd' 'BsmtQual_TA' 'BsmtCond_Fa'
 'BsmtCond_Gd' 'BsmtCond_Po' 'BsmtCond_TA' 'BsmtExposure_Av'
 'BsmtExposure_Gd' 'BsmtExposure_Mn' 'BsmtExposure_No' 'BsmtFinType1_ALQ'
 'BsmtFinType1_BLQ' 'BsmtFinType1_GLQ' 'BsmtFinType1_LwQ'
 'BsmtFinType1_Rec' 'BsmtFinType1_Unf' 'BsmtFinType2_ALQ'
 'BsmtFinType2_BLQ' 'BsmtFinType2_GLQ' 'BsmtFinType2_LwQ'
 'BsmtFinType2_Rec' 'BsmtFinType2_Unf' 'Heating_Floor' 'Heating_GasA'
 'Heating_GasW' 'Heating_Grav' 'Heating_OthW' 'Heating_Wall'
 'HeatingQC_Ex' 'HeatingQC_Fa' 'HeatingQC_Gd' 'HeatingQC_Po'
 'HeatingQC_TA' 'CentralAir_N' 'CentralAir_Y' 'Electrical_FuseA'
 'Electrical_FuseF' 'Electrical_FuseP' 'Electrical_Mix' 'Electrical_SBrkr'
 'KitchenQual_Ex' 'KitchenQual_Fa' 'KitchenQual_Gd' 'KitchenQual_TA'
 'Functional_Maj1' 'Functional_Maj2' 'Functional_Min1' 'Functional_Min2'
 'Functional_Mod' 'Functional_Sev' 'Functional_Typ' 'GarageType_2Types'
 'GarageType_Attchd' 'GarageType_Basment' 'GarageType_BuiltIn'
 'GarageType_CarPort' 'GarageType_Detchd' 'GarageFinish_Fin'
 'GarageFinish_RFn' 'GarageFinish_Unf' 'GarageQual_Ex' 'GarageQual_Fa'
 'GarageQual_Gd' 'GarageQual_Po' 'GarageQual_TA' 'GarageCond_Ex'
 'GarageCond_Fa' 'GarageCond_Gd' 'GarageCond_Po' 'GarageCond_TA'
 'PavedDrive_N' 'PavedDrive_P' 'PavedDrive_Y' 'SaleType_COD'
 'SaleType_CWD' 'SaleType_Con' 'SaleType_ConLD' 'SaleType_ConLI'
 'SaleType_ConLw' 'SaleType_New' 'SaleType_Oth' 'SaleType_WD'
 'SaleCondition_Abnorml' 'SaleCondition_AdjLand' 'SaleCondition_Alloca'
 'SaleCondition_Family' 'SaleCondition_Normal' 'SaleCondition_Partial']
Number of input features: 267

File:
D:\AI-Lab-99\House Price\model_columns.pkl
Object type: list

File:
D:\AI-Lab-99\Week 4\Module 6 Customer Segmentation Model Development\feature_list.pkl
Object type: list

File:
D:\AI-Lab-99\Week 4\Module 6 Customer Segmentation Model Development\standard_scaler.pkl
Object type: DataFrame

In [ ]:

# COMPARE DATASET FEATURES WITH MODEL

model_feature_count = getattr(
    kmeans_model,
    "n_features_in_",
    None
)

print("Model expects:", model_feature_count)
print("Dataset numeric features:", len(numeric_features))

print("\nComparison")
print("=" * 60)

if model_feature_count == len(numeric_features):

    print(
        " Number of numeric features matches model input."
    )

else:

    print(
        " Number does NOT match."
    )

    print(
        "We need to identify the exact training features "
        "before prediction."
    )

Model expects: 40
Dataset numeric features: 40

Comparison
============================================================
✅ Number of numeric features matches model input.

In [ ]:

# SEARCH ALL ML MODEL / PREPROCESSING FILES


print("Searching D:\\AI-Lab-99 for ML files...")
print("=" * 60)

ml_files = []

for root, dirs, files in os.walk(base_path):

    for file in files:

        lower_name = file.lower()

        if (
            lower_name.endswith(".pkl")
            or lower_name.endswith(".joblib")
        ):

            ml_files.append(
                os.path.join(root, file)
            )


for path in ml_files:

    print("", path)


print("\nTotal ML files found:", len(ml_files))

Searching D:\AI-Lab-99 for ML files...
============================================================
📁 D:\AI-Lab-99\3_Titanic_preprocessing\preprocessing_pipeline.joblib
📁 D:\AI-Lab-99\House Price\best_model.pkl
📁 D:\AI-Lab-99\House Price\model_columns.pkl
📁 D:\AI-Lab-99\Week 4\Module 6 Customer Segmentation Model Development\feature_list.pkl
📁 D:\AI-Lab-99\Week 4\Module 6 Customer Segmentation Model Development\kmeans_model.pkl
📁 D:\AI-Lab-99\Week 4\Module 6 Customer Segmentation Model Development\standard_scaler.pkl

Total ML files found: 6

## TASK 3 — FIND MODULE

In [ ]:
module7_files = []

for root, dirs, files in os.walk(base_path):

    for file in files:

        file_lower = file.lower()

        if file_lower.endswith(".ipynb"):

            if (
                "module 7" in file_lower
                or "module7" in file_lower
                or "cluster" in file_lower
                or "customer" in file_lower
            ):
                module7_files.append(
                    os.path.join(root, file)
                )


print("Possible Module 7 notebooks:")
print("=" * 60)

for path in module7_files:
    print("", path)

print("\nTotal found:", len(module7_files))

Possible Module 7 notebooks:
============================================================

Total found: 0

In [ ]:

# FIND MODULE 7 PYTHON FILES


python_files = []

for root, dirs, files in os.walk(base_path):

    for file in files:

        file_lower = file.lower()

        if file_lower.endswith(".py"):

            if (
                "cluster" in file_lower
                or "module7" in file_lower
                or "module_7" in file_lower
            ):
                python_files.append(
                    os.path.join(root, file)
                )


print("Possible Module 7 Python files:")
print("=" * 60)

for path in python_files:
    print("", path)

print("\nTotal found:", len(python_files))

Possible Module 7 Python files:
============================================================

Total found: 0

In [ ]:

# TASK 3 STATUS


print("TASK 3 — FEATURE ENGINEERING STATUS")
print("=" * 60)

if hasattr(kmeans_model, "feature_names_in_"):

    print(" Exact feature names found directly in model.")

elif preprocessing_files:

    print(" Saved preprocessing/model artifacts available.")

elif module7_files or python_files:

    print(" Module 7 source files available for feature recovery.")

else:

    print(" Training feature information is not directly available.")
    print("We will inspect the Module 7 workflow.")

TASK 3 — FEATURE ENGINEERING STATUS
============================================================
✅ Exact feature names found directly in model.

## TASK 4 — IDENTIFY FINAL MODEL FEATURES

In [ ]:
model_features = None

# First priority: feature names stored in model
if hasattr(kmeans_model, "feature_names_in_"):

    model_features = list(
        kmeans_model.feature_names_in_
    )

    print(" Features recovered from K-Means model.")

# Second priority: preprocessing object
elif preprocessing_files:

    for path in preprocessing_files:

        try:

            obj = joblib.load(path)

            if hasattr(obj, "feature_names_in_"):

                model_features = list(
                    obj.feature_names_in_
                )

                print(
                    " Features recovered from preprocessing file:"
                )
                print(path)

                break

        except Exception:
            pass


if model_features is not None:

    print("\nExact model features:")
    print("=" * 60)

    for i, feature in enumerate(model_features, start=1):

        print(f"{i:02d}. {feature}")

else:

    print(
        " Exact feature names could not be recovered automatically."
    )

✅ Features recovered from K-Means model.

Exact model features:
============================================================
01. Education
02. Marital_Status
03. Income
04. Recency
05. MntWines
06. MntFruits
07. MntMeatProducts
08. MntFishProducts
09. MntSweetProducts
10. MntGoldProds
11. NumDealsPurchases
12. NumWebPurchases
13. NumCatalogPurchases
14. NumStorePurchases
15. NumWebVisitsMonth
16. AcceptedCmp3
17. AcceptedCmp4
18. AcceptedCmp5
19. AcceptedCmp1
20. AcceptedCmp2
21. Complain
22. Response
23. Age
24. Year
25. Month
26. Day
27. Customer_Age
28. Customer_Tenure
29. Total_Children
30. Partner
31. Family_size
32. Total_spending
33. Total_Purchase
34. Total_Campaign
35. Average Spending per Purchase
36. Digital_Engagement
37. Deal_Dependency
38. Preferred_Shopping_Channel
39. Product_Preference
40. Customer_Activity_Level

In [ ]:

# VERIFY MODEL FEATURES AGAINST FINAL DATASET


if model_features is not None:

    missing_features = [
        feature
        for feature in model_features
        if feature not in df.columns
    ]

    available_features = [
        feature
        for feature in model_features
        if feature in df.columns
    ]

    print("Required model features:", len(model_features))
    print("Available in dataset:", len(available_features))
    print("Missing:", len(missing_features))

    if missing_features:

        print("\n Missing features:")
        for feature in missing_features:
            print("→", feature)

    else:

        print("\n ALL MODEL FEATURES ARE PRESENT.")

else:

    print(
        " Cannot verify until model features are identified."
    )

Required model features: 40
Available in dataset: 40
Missing: 0

✅ ALL MODEL FEATURES ARE PRESENT.

In [ ]:

# CREATE EXACT MODEL INPUT


if model_features is not None:

    X_model = df[model_features].copy()

    print(" Exact model input created.")

    print("\nShape:")
    print(X_model.shape)

    print("\nColumns:")
    print(X_model.columns.tolist())

    print("\nFirst 5 rows:")
    display(X_model.head())

✅ Exact model input created.

Shape:
(2038, 40)

Columns:
['Education', 'Marital_Status', 'Income', 'Recency', 'MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts', 'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth', 'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1', 'AcceptedCmp2', 'Complain', 'Response', 'Age', 'Year', 'Month', 'Day', 'Customer_Age', 'Customer_Tenure', 'Total_Children', 'Partner', 'Family_size', 'Total_spending', 'Total_Purchase', 'Total_Campaign', 'Average Spending per Purchase', 'Digital_Engagement', 'Deal_Dependency', 'Preferred_Shopping_Channel', 'Product_Preference', 'Customer_Activity_Level']

First 5 rows:

,Education,Marital_Status,Income,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,...,Family_size,Total_spending,Total_Purchase,Total_Campaign,Average Spending per Purchase,Digital_Engagement,Deal_Dependency,Preferred_Shopping_Channel,Product_Preference,Customer_Activity_Level
0,-0.458383,1.251776,0.299651,0.307039,0.989643,1.470132,1.442724,1.434322,1.455038,1.121518,...,-1.759115,1.219788,1.380023,0.0,1.176601,1.620481,-0.514589,-2.187642,0.512133,1.276773
1,-0.458383,1.251776,-0.263808,-0.383664,-1.213866,-1.000697,-1.415023,-0.874095,-0.986677,-0.921817,...,0.446548,-1.567145,-1.163336,0.0,-1.629866,-0.965311,1.417872,-0.361890,0.512133,-1.211241
2,-0.458383,-0.272125,0.943420,-0.798086,0.768523,1.140985,0.490422,1.383545,0.589966,0.536950,...,-0.656283,0.739374,0.844579,0.0,0.592428,0.758551,-1.255068,-0.361890,0.512133,1.276773
3,-0.458383,-0.272125,-1.204881,-0.798086,-1.213866,-0.391042,-0.694700,-0.063762,-0.530925,-1.045693,...,0.446548,-1.111302,-0.895614,0.0,-1.254015,-0.390691,0.702554,-0.361890,-0.653942,-1.211241
4,1.533425,-0.272125,0.307056,1.550305,0.270284,1.055931,0.442620,0.841975,0.748533,-0.257498,...,0.446548,0.317339,0.576857,0.0,0.026695,0.183930,0.818614,-0.361890,0.512133,0.032766

## TASK 7 — TEST K-MEANS PREDICTION

In [ ]:




if model_features is not None:

    X_test = X_model.iloc[[0]]

    try:

        prediction = kmeans_model.predict(X_test)

        print(" Prediction successful!")

        print(
            "First customer predicted cluster:",
            prediction[0]
        )

    except Exception as e:

        print(" Prediction failed.")

        print("\nError:")
        print(e)

✅ Prediction successful!
First customer predicted cluster: 0

## TASK 8 — CUSTOMER SEGMENT PREDICTION

In [ ]:
def predict_customer_segment(customer_data):

    try:
        # Make sure columns are in exact model order
        customer_data = customer_data[model_features]

        # Predict cluster
        cluster_prediction = kmeans_model.predict(
            customer_data
        )[0]

        return int(cluster_prediction)

    except Exception as e:

        print(" Prediction Error:")
        print(e)

        return None

In [ ]:

# BUSINESS SEGMENT MAPPING


if "Customer_Segment" in df.columns:

    segment_mapping = (
        df[["Cluster", "Customer_Segment"]]
        .drop_duplicates()
        .sort_values("Cluster")
    )

    print("Existing Cluster → Business Segment mapping")
    print("=" * 60)

    display(segment_mapping)

else:

    print(" Customer_Segment column not found.")

⚠️ Customer_Segment column not found.

In [ ]:

# PREDICTION RESULT


sample_customer = X_model.iloc[[0]].copy()

predicted_cluster = predict_customer_segment(
    sample_customer
)

print("Predicted Cluster:", predicted_cluster)

Predicted Cluster: 0

In [ ]:

# CLUSTER → BUSINESS SEGMENT


if predicted_cluster is not None:

    if "Cluster" in df.columns and "Customer_Segment" in df.columns:

        mapping = (
            df[["Cluster", "Customer_Segment"]]
            .drop_duplicates()
        )

        match = mapping[
            mapping["Cluster"] == predicted_cluster
        ]

        if not match.empty:

            business_segment = match[
                "Customer_Segment"
            ].iloc[0]

            print("Predicted Cluster:", predicted_cluster)
            print(
                "Business Segment:",
                business_segment
            )

        else:

            business_segment = "Unknown Segment"

            print(
                " Business segment not found."
            )

    else:

        business_segment = f"Cluster {predicted_cluster}"

        print(
            "Predicted Cluster:",
            predicted_cluster
        )

Predicted Cluster: 0

## TASK 9 — CHECK ACTUAL SEGMENT COLUMN

In [ ]:
print("Available columns:")
print("=" * 60)

for i, col in enumerate(df.columns, start=1):
    print(f"{i:02d}. {col}")

print("\nPossible segment columns:")

for col in df.columns:
    if any(word in col.lower() for word in [
        "cluster",
        "segment",
        "group",
        "label"
    ]):
        print("", col)

Available columns:
============================================================
01. Education
02. Marital_Status
03. Income
04. Recency
05. MntWines
06. MntFruits
07. MntMeatProducts
08. MntFishProducts
09. MntSweetProducts
10. MntGoldProds
11. NumDealsPurchases
12. NumWebPurchases
13. NumCatalogPurchases
14. NumStorePurchases
15. NumWebVisitsMonth
16. AcceptedCmp3
17. AcceptedCmp4
18. AcceptedCmp5
19. AcceptedCmp1
20. AcceptedCmp2
21. Complain
22. Response
23. Age
24. Year
25. Month
26. Day
27. Customer_Age
28. Customer_Tenure
29. Total_Children
30. Partner
31. Family_size
32. Total_spending
33. Total_Purchase
34. Total_Campaign
35. Average Spending per Purchase
36. Digital_Engagement
37. Deal_Dependency
38. Preferred_Shopping_Channel
39. Product_Preference
40. Customer_Activity_Level

Possible segment columns:

In [ ]:

# FIND SEGMENT COLUMN AUTOMATICALLY


segment_col = None

for col in df.columns:

    if col.lower() == "cluster":
        segment_col = col
        break

    if "cluster" in col.lower():
        segment_col = col
        break

    if "segment" in col.lower():
        segment_col = col
        break


if segment_col:

    print(" Segment column found:")
    print(segment_col)

    print("\nValues:")
    print(df[segment_col].value_counts())

else:

    print(" No Cluster/Segment column found.")

❌ No Cluster/Segment column found.

In [ ]:

#PREDICT CLUSTER FOR ALL CUSTOMERS


print(" Predicting clusters for all customers...")

# Use the exact model features identified earlier
X_all = df[model_features].copy()

# Predict cluster for every customer
all_predictions = kmeans_model.predict(X_all)

# Add predictions temporarily
df_analysis = df.copy()

df_analysis["Predicted_Cluster"] = all_predictions

print(" Cluster prediction completed!")

print("\nCluster distribution:")
print(df_analysis["Predicted_Cluster"].value_counts().sort_index())

🔄 Predicting clusters for all customers...
✅ Cluster prediction completed!

Cluster distribution:
Predicted_Cluster
0    1111
1     927
Name: count, dtype: int64

In [ ]:

# CREATE SEGMENT CUSTOMERS


# Use the cluster predicted for the selected customer
segment_customers = df_analysis[
    df_analysis["Predicted_Cluster"] == predicted_cluster
].copy()

print(" Segment customers created!")

print("Predicted Cluster:", predicted_cluster)

print(
    "Customers in this segment:",
    len(segment_customers)
)

display(segment_customers.head())

✅ Segment customers created!
Predicted Cluster: 0
Customers in this segment: 1111

,Education,Marital_Status,Income,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,...,Total_spending,Total_Purchase,Total_Campaign,Average Spending per Purchase,Digital_Engagement,Deal_Dependency,Preferred_Shopping_Channel,Product_Preference,Customer_Activity_Level,Predicted_Cluster
0,-0.458383,1.251776,0.299651,0.307039,0.989643,1.470132,1.442724,1.434322,1.455038,1.121518,...,1.219788,1.380023,0.0,1.176601,1.620481,-0.514589,-2.187642,0.512133,1.276773,0
2,-0.458383,-0.272125,0.943420,-0.798086,0.768523,1.140985,0.490422,1.383545,0.589966,0.536950,...,0.739374,0.844579,0.0,0.592428,0.758551,-1.255068,-0.361890,0.512133,1.276773,0
4,1.533425,-0.272125,0.307056,1.550305,0.270284,1.055931,0.442620,0.841975,0.748533,-0.257498,...,0.317339,0.576857,0.0,0.026695,0.183930,0.818614,-0.361890,0.512133,0.032766,0
5,0.537521,-0.272125,0.508667,-1.143438,0.878949,1.040635,0.321975,-1.559274,1.030602,-0.309361,...,0.683596,0.978440,0.0,0.450420,0.758551,-0.806279,-0.361890,0.512133,1.276773,0
6,-0.458383,-1.796026,0.180070,-0.521805,0.439435,1.325708,0.656906,0.892915,1.129770,0.192209,...,0.549463,0.844579,0.0,0.286673,1.045861,0.161784,1.463862,0.512133,1.276773,0

In [ ]:

# 35 — SEGMENT SUMMARY


print(" SEGMENT SUMMARY")
print("=" * 60)

summary_data = {
    "Metric": [],
    "Value": []
}

summary_data["Metric"].append("Customers")
summary_data["Value"].append(
    len(segment_customers)
)

if "Income" in segment_customers.columns:

    summary_data["Metric"].append(
        "Average Income"
    )

    summary_data["Value"].append(
        round(
            segment_customers["Income"].mean(),
            2
        )
    )

if "Total_spending" in segment_customers.columns:

    summary_data["Metric"].append(
        "Average Total Spending"
    )

    summary_data["Value"].append(
        round(
            segment_customers["Total_spending"].mean(),
            2
        )
    )

if "Recency" in segment_customers.columns:

    summary_data["Metric"].append(
        "Average Recency"
    )

    summary_data["Value"].append(
        round(
            segment_customers["Recency"].mean(),
            2
        )
    )

segment_summary = pd.DataFrame(
    summary_data
)

display(segment_summary)

📊 SEGMENT SUMMARY
============================================================

                   Metric    Value
0               Customers  1111.00
1          Average Income     0.67
2  Average Total Spending     0.81
3         Average Recency     0.01

In [ ]:

#   PURCHASE BEHAVIOR

purchase_columns = [
    "NumDealsPurchases",
    "NumWebPurchases",
    "NumCatalogPurchases",
    "NumStorePurchases",
    "NumWebVisitsMonth"
]

available_purchase_columns = [
    col for col in purchase_columns
    if col in segment_customers.columns
]

print(" PURCHASE BEHAVIOR")
print("=" * 60)

if available_purchase_columns:

    purchase_behavior = (
        segment_customers[available_purchase_columns]
        .mean()
        .sort_values(ascending=False)
        .to_frame("Average Value")
    )

    display(purchase_behavior)

else:
    print(" Purchase columns not found.")

🛒 PURCHASE BEHAVIOR
============================================================

                     Average Value
NumCatalogPurchases       0.730935
NumStorePurchases         0.706337
NumWebPurchases           0.657433
NumDealsPurchases         0.039798
NumWebVisitsMonth        -0.395373

In [ ]:

#  PRODUCT PREFERENCE


product_columns = [
    "MntWines",
    "MntFruits",
    "MntMeatProducts",
    "MntFishProducts",
    "MntSweetProducts",
    "MntGoldProds"
]

available_product_columns = [
    col for col in product_columns
    if col in segment_customers.columns
]

print(" PRODUCT PREFERENCE")
print("=" * 60)

if available_product_columns:

    product_preferences = (
        segment_customers[available_product_columns]
        .mean()
        .sort_values(ascending=False)
        .to_frame("Average Spending")
    )

    display(product_preferences)

    preferred_product = product_preferences.index[0]

    print(
        " Preferred Product:",
        preferred_product
    )

else:
    print(" Product columns not found.")

🛍️ PRODUCT PREFERENCE
============================================================

                  Average Spending
MntWines                  0.759971
MntMeatProducts           0.758317
MntFruits                 0.577810
MntFishProducts           0.571659
MntGoldProds              0.560285
MntSweetProducts          0.553149

⭐ Preferred Product: MntWines

In [ ]:

#  CAMPAIGN RESPONSE


campaign_columns = [
    "AcceptedCmp1",
    "AcceptedCmp2",
    "AcceptedCmp3",
    "AcceptedCmp4",
    "AcceptedCmp5",
    "Response"
]

available_campaign_columns = [
    col for col in campaign_columns
    if col in segment_customers.columns
]

print(" CAMPAIGN RESPONSE")
print("=" * 60)

if available_campaign_columns:

    campaign_response = (
        segment_customers[available_campaign_columns]
        .mean()
        .sort_values(ascending=False)
        .to_frame("Response Rate")
    )

    display(campaign_response)

else:
    print(" Campaign columns not found.")

📢 CAMPAIGN RESPONSE
============================================================

              Response Rate
AcceptedCmp1            0.0
AcceptedCmp2            0.0
AcceptedCmp3            0.0
AcceptedCmp4            0.0
AcceptedCmp5            0.0
Response                0.0

In [ ]:

#  CUSTOMER ACTIVITY & RISK


print(" CUSTOMER ACTIVITY & RISK")
print("=" * 60)

if "Customer_Activity_Level" in segment_customers.columns:

    activity_counts = (
        segment_customers["Customer_Activity_Level"]
        .value_counts()
    )

    print("Activity Levels:")
    display(activity_counts.to_frame("Customers"))

    activity_level = activity_counts.index[0]

    print(
        " Dominant Activity Level:",
        activity_level
    )

else:

    activity_level = "Unknown"

    print(" Customer_Activity_Level not found.")

👤 CUSTOMER ACTIVITY & RISK
============================================================
Activity Levels:

                         Customers
Customer_Activity_Level
 1.276773                      625
 0.032766                      466
-1.211241                       20

⭐ Dominant Activity Level: 1.2767732631531177

In [ ]:
if "Recency" in segment_customers.columns:

    avg_recency = segment_customers["Recency"].mean()

    if avg_recency <= 30:
        risk_level = "Very Low"

    elif avg_recency <= 60:
        risk_level = "Low"

    elif avg_recency <= 90:
        risk_level = "Medium"

    else:
        risk_level = "High"

    print("Average Recency:", round(avg_recency, 2))
    print("Risk Level:", risk_level)

else:

    risk_level = "Unknown"
    print(" Recency not available.")

Average Recency: 0.01
Risk Level: Very Low

In [ ]:

#  CUSTOMER PERSONA SUMMARY


print(" CUSTOMER PERSONA")
print("=" * 60)

print("Predicted Cluster     :", predicted_cluster)
print("Number of Customers   :", len(segment_customers))

if "Income" in segment_customers.columns:
    print(
        "Average Income        :",
        round(segment_customers["Income"].mean(), 2)
    )

if "Total_spending" in segment_customers.columns:
    print(
        "Average Spending      :",
        round(segment_customers["Total_spending"].mean(), 2)
    )

if "Recency" in segment_customers.columns:
    print(
        "Average Recency       :",
        round(segment_customers["Recency"].mean(), 2)
    )

print("Activity Level        :", activity_level)
print("Risk Level            :", risk_level)

if "preferred_product" in globals():
    print("Preferred Product     :", preferred_product)

👤 CUSTOMER PERSONA
============================================================
Predicted Cluster     : 0
Number of Customers   : 1111
Average Income        : 0.67
Average Spending      : 0.81
Average Recency       : 0.01
Activity Level        : 1.2767732631531177
Risk Level            : Very Low
Preferred Product     : MntWines

In [ ]:

#  MARKETING RECOMMENDATION LOGIC


# 1. COMMUNICATION CHANNEL


if "Preferred_Shopping_Channel" in segment_customers.columns:

    channel_counts = (
        segment_customers["Preferred_Shopping_Channel"]
        .value_counts()
    )

    preferred_channel = channel_counts.index[0]

else:

    preferred_channel = "Email"


# 2. DISCOUNT / OFFER STRATEGY

if "Deal_Dependency" in segment_customers.columns:

    deal_values = (
        segment_customers["Deal_Dependency"]
        .astype(str)
        .str.lower()
    )

    if deal_values.str.contains("high").mean() > 0.5:

        discount_strategy = "Special Discount / Coupon"
        personalized_offer = "Limited-Time Discount Offer"

    else:

        discount_strategy = "Low Discount / Value-Based Offer"
        personalized_offer = "Exclusive Product Offer"

else:

    discount_strategy = "Personalized Offer"
    personalized_offer = "Special Customer Offer"



# 3. MARKETING MESSAGE


if risk_level in ["High", "Medium"]:

    marketing_message = (
        "We Miss You! Come Back and Enjoy "
        "a Special Personalized Offer"
    )

    campaign_timing = "Immediate Win-Back Campaign"

elif "Total_spending" in segment_customers.columns:

    segment_spending = (
        segment_customers["Total_spending"].mean()
    )

    overall_spending = df["Total_spending"].mean()

    if segment_spending > overall_spending:

        marketing_message = (
            "Enjoy Exclusive Rewards and "
            "Premium Products Selected for You"
        )

        campaign_timing = "Weekly"

    else:

        marketing_message = (
            "Discover Great Products and "
            "Save More with Personalized Offers"
        )

        campaign_timing = "Bi-Weekly"

else:

    marketing_message = (
        "Discover Products Selected Especially for You"
    )

    campaign_timing = "Bi-Weekly"



# 4. PRODUCT RECOMMENDATION


if "preferred_product" in globals():

    primary_product = preferred_product

else:

    primary_product = "Personalized Product Category"



# 5. RETENTION STRATEGY


if risk_level == "High":

    retention_strategy = (
        "Priority retention campaign with "
        "win-back offer"
    )

elif risk_level == "Medium":

    retention_strategy = (
        "Regular engagement and personalized offers"
    )

else:

    retention_strategy = (
        "Loyalty rewards and exclusive benefits"
    )


print(" Marketing recommendations generated.")

✅ Marketing recommendations generated.

In [ ]:

# CROSS-SELLING & UPSELLING


product_order = []

if "product_preferences" in globals():

    product_order = list(
        product_preferences.index
    )


# Primary product
if len(product_order) >= 1:

    primary_product = product_order[0]

else:

    primary_product = "Personalized Product"


# Secondary product
if len(product_order) >= 2:

    secondary_product = product_order[1]

else:

    secondary_product = "Complementary Product"


# Cross-selling
cross_selling = (
    f"Recommend {secondary_product} "
    f"with {primary_product}"
)


# Upselling
upselling = (
    f"Offer premium or higher-value "
    f"{primary_product} products"
)


print("Primary Product :", primary_product)
print("Secondary Product:", secondary_product)
print("Cross-Selling   :", cross_selling)
print("Upselling       :", upselling)

Primary Product : MntWines
Secondary Product: MntMeatProducts
Cross-Selling   : Recommend MntMeatProducts with MntWines
Upselling       : Offer premium or higher-value MntWines products

In [ ]:

# FINAL MARKETING RECOMMENDATION


marketing_recommendation = pd.DataFrame({
    
    "Recommendation": [
        "Marketing Message",
        "Communication Channel",
        "Personalized Offer",
        "Campaign Timing",
        "Campaign Frequency",
        "Primary Product",
        "Secondary Product",
        "Cross-Selling",
        "Upselling",
        "Discount Strategy",
        "Retention Strategy",
        "Risk Level"
    ],
    
    "Recommendation Details": [
        marketing_message,
        preferred_channel,
        personalized_offer,
        campaign_timing,
        "Weekly" if risk_level == "Low" else "Bi-Weekly",
        primary_product,
        secondary_product,
        cross_selling,
        upselling,
        discount_strategy,
        retention_strategy,
        risk_level
    ]
})


print(" FINAL MARKETING RECOMMENDATION")
print("=" * 70)

display(marketing_recommendation)

📢 FINAL MARKETING RECOMMENDATION
======================================================================

           Recommendation                             Recommendation Details
0       Marketing Message  Enjoy Exclusive Rewards and Premium Products S...
1   Communication Channel                                           -0.36189
2      Personalized Offer                            Exclusive Product Offer
3         Campaign Timing                                             Weekly
4      Campaign Frequency                                          Bi-Weekly
5         Primary Product                                           MntWines
6       Secondary Product                                    MntMeatProducts
7           Cross-Selling            Recommend MntMeatProducts with MntWines
8               Upselling    Offer premium or higher-value MntWines products
9       Discount Strategy                   Low Discount / Value-Based Offer
10     Retention Strategy             Loyalty rewards and exclusive benefits
11             Risk Level                                           Very Low

In [ ]:

#  COMPLETE CUSTOMER PROFILE

print(" CUSTOMER SEGMENT PROFILE")
print("=" * 70)

profile = {
    "Predicted Cluster": predicted_cluster,
    "Customers in Segment": len(segment_customers),
    "Activity Level": activity_level,
    "Risk Level": risk_level,
    "Preferred Channel": preferred_channel,
    "Primary Product": primary_product,
    "Secondary Product": secondary_product,
    "Marketing Message": marketing_message,
    "Personalized Offer": personalized_offer,
    "Discount Strategy": discount_strategy,
    "Retention Strategy": retention_strategy
}

for key, value in profile.items():
    print(f"{key}: {value}")

👤 CUSTOMER SEGMENT PROFILE
======================================================================
Predicted Cluster: 0
Customers in Segment: 1111
Activity Level: 1.2767732631531177
Risk Level: Very Low
Preferred Channel: -0.3618900416669088
Primary Product: MntWines
Secondary Product: MntMeatProducts
Marketing Message: Enjoy Exclusive Rewards and Premium Products Selected for You
Personalized Offer: Exclusive Product Offer
Discount Strategy: Low Discount / Value-Based Offer
Retention Strategy: Loyalty rewards and exclusive benefits

In [ ]:

# CELL 45 — SAVE DAY 3 RESULTS FOR STREAMLIT

import joblib
from pathlib import Path


# STREAMLIT APP FOLDER


app_folder = Path(
  r"D:\AI-Lab-99\Week 5\Day 3"
)

# Make sure folder exists
app_folder.mkdir(parents=True, exist_ok=True)

# Output file
output_file = app_folder / "day3_results.pkl"


# -----------------------------------------------------
# COLLECT DAY 3 RESULTS
# -----------------------------------------------------

day3_results = {
    "predicted_cluster": predicted_cluster,
    "customers_in_segment": len(segment_customers),

    "activity_level": activity_level,
    "risk_level": risk_level,

    "preferred_channel": preferred_channel,
    "marketing_message": marketing_message,
    "personalized_offer": personalized_offer,
    "campaign_timing": campaign_timing,
    "discount_strategy": discount_strategy,
    "retention_strategy": retention_strategy,

    "primary_product": primary_product,
    "secondary_product": secondary_product,

    "cross_selling": cross_selling,
    "upselling": upselling,

    "segment_summary": segment_summary,
    "marketing_recommendation": marketing_recommendation,

    "segment_customers": segment_customers
}


# -----------------------------------------------------
# SAVE RESULTS
# -----------------------------------------------------

try:

    joblib.dump(day3_results, output_file)

    print(" DAY 3 RESULTS SAVED SUCCESSFULLY")
    print("=" * 60)
    print("File:")
    print(output_file)

    print("\nSaved items:")

    for key in day3_results.keys():
        print("✓", key)

except Exception as e:

    print(" ERROR WHILE SAVING DAY 3 RESULTS")
    print("=" * 60)
    print(type(e).__name__)
    print(e)

✅ DAY 3 RESULTS SAVED SUCCESSFULLY
============================================================
File:
D:\AI-Lab-99\Week 5\Day 3\day3_results.pkl

Saved items:
✓ predicted_cluster
✓ customers_in_segment
✓ activity_level
✓ risk_level
✓ preferred_channel
✓ marketing_message
✓ personalized_offer
✓ campaign_timing
✓ discount_strategy
✓ retention_strategy
✓ primary_product
✓ secondary_product
✓ cross_selling
✓ upselling
✓ segment_summary
✓ marketing_recommendation
✓ segment_customers