In [22]:

# DAY 4 — QUALITY ASSURANCE
# Customer Personality Analysis

print("DAY 4 — QUALITY ASSURANCE")
print("=" * 60)
print("Testing Dataset, Model, Day 3 Results & Streamlit Outputs")

DAY 4 — QUALITY ASSURANCE
============================================================
Testing Dataset, Model, Day 3 Results & Streamlit Outputs

In [23]:
import os
import joblib
import pandas as pd
import numpy as np
from pathlib import Path

print("✅ Libraries imported successfully")

✅ Libraries imported successfully

In [24]:
BASE_PATH = Path(r"D:\AI-Lab-99")

WEEK5_PATH = BASE_PATH / "Week 5"

DATA_PATH = WEEK5_PATH / "Day 1" / "Final Dataset.csv"
MODEL_PATH = WEEK5_PATH / "Day 4" / "kmeans_model.pkl"
RESULTS_PATH = WEEK5_PATH / "Day 4" / "day3_results.pkl"

print("DATA:", DATA_PATH)
print("MODEL:", MODEL_PATH)
print("RESULTS:", RESULTS_PATH)

DATA: D:\AI-Lab-99\Week 5\Day 1\Final Dataset.csv
MODEL: D:\AI-Lab-99\Week 5\Day 4\kmeans_model.pkl
RESULTS: D:\AI-Lab-99\Week 5\Day 4\day3_results.pkl

In [25]:
def find_file(filename, base_path):
    for root, dirs, files in os.walk(base_path):
        if filename in files:
            return Path(root) / filename
    return None


csv_path = find_file("Final Dataset.csv", BASE_PATH)
model_path = find_file("kmeans_model.pkl", BASE_PATH)
results_path = find_file("day3_results.pkl", BASE_PATH)

print(" FILE DETECTION")
print("=" * 60)

print("Final Dataset.csv :", csv_path)
print("kmeans_model.pkl  :", model_path)
print("day3_results.pkl  :", results_path)

 FILE DETECTION
============================================================
Final Dataset.csv : D:\AI-Lab-99\Week 5\Day 1\Final Dataset.csv
kmeans_model.pkl  : D:\AI-Lab-99\Week 4\Module 6 Customer Segmentation Model Development\kmeans_model.pkl
day3_results.pkl  : D:\AI-Lab-99\Week 3\week4\Module 8 Business Insights and Marketing Recommendations\day3_results.pkl

In [26]:
qa_files = {
    "Final Dataset.csv": csv_path,
    "kmeans_model.pkl": model_path,
    "day3_results.pkl": results_path
}

qa_file_results = []

for name, path in qa_files.items():
    status = "PASS" if path is not None and path.exists() else "FAIL"
    
    qa_file_results.append({
        "Test": name,
        "Status": status,
        "Path": str(path) if path else "Not Found"
    })

file_test_df = pd.DataFrame(qa_file_results)

display(file_test_df)

                Test Status                                               Path
0  Final Dataset.csv   PASS        D:\AI-Lab-99\Week 5\Day 1\Final Dataset.csv
1   kmeans_model.pkl   PASS  D:\AI-Lab-99\Week 4\Module 6 Customer Segmenta...
2   day3_results.pkl   PASS  D:\AI-Lab-99\Week 3\week4\Module 8 Business In...

In [28]:
df = pd.read_csv(csv_path)

print(" Dataset loaded successfully")
print("Rows:", len(df))
print("Columns:", len(df.columns))

display(df.head())

 Dataset loaded successfully
Rows: 2038
Columns: 42

,Education,Marital_Status,Income,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,...,Total_Purchase,Total_Campaign,Average Spending per Purchase,Digital_Engagement,Deal_Dependency,Preferred_Shopping_Channel,Product_Preference,Customer_Activity_Level,Cluster,Customer_Segment
0,-0.458383,1.251776,0.299651,0.307039,0.989643,1.470132,1.442724,1.434322,1.455038,1.121518,...,1.380023,0.0,1.176601,1.620481,-0.514589,-2.187642,0.512133,1.276773,0,Premium Loyal Customers
1,-0.458383,1.251776,-0.263808,-0.383664,-1.213866,-1.000697,-1.415023,-0.874095,-0.986677,-0.921817,...,-1.163336,0.0,-1.629866,-0.965311,1.417872,-0.361890,0.512133,-1.211241,1,Digital-First Buyers
2,-0.458383,-0.272125,0.943420,-0.798086,0.768523,1.140985,0.490422,1.383545,0.589966,0.536950,...,0.844579,0.0,0.592428,0.758551,-1.255068,-0.361890,0.512133,1.276773,0,Premium Loyal Customers
3,-0.458383,-0.272125,-1.204881,-0.798086,-1.213866,-0.391042,-0.694700,-0.063762,-0.530925,-1.045693,...,-0.895614,0.0,-1.254015,-0.390691,0.702554,-0.361890,-0.653942,-1.211241,1,Digital-First Buyers
4,1.533425,-0.272125,0.307056,1.550305,0.270284,1.055931,0.442620,0.841975,0.748533,-0.257498,...,0.576857,0.0,0.026695,0.183930,0.818614,-0.361890,0.512133,0.032766,0,Premium Loyal Customers

In [29]:
print("DATASET QUALITY CHECK")
print("=" * 60)

print("Shape:", df.shape)
print("Duplicate rows:", df.duplicated().sum())
print("Missing values:", df.isnull().sum().sum())

if "ID" in df.columns:
    print("Duplicate IDs:", df["ID"].duplicated().sum())

DATASET QUALITY CHECK
============================================================
Shape: (2038, 42)
Duplicate rows: 0
Missing values: 0

In [30]:
required_columns = [
    "Income",
    "Recency",
    "Age",
    "Total_spending",
    "Total_Purchase",
    "Family_size",
    "NumWebPurchases",
    "NumStorePurchases",
    "NumCatalogPurchases"
]

column_test = []

for col in required_columns:
    column_test.append({
        "Column": col,
        "Status": "PASS" if col in df.columns else "FAIL"
    })

column_test_df = pd.DataFrame(column_test)

display(column_test_df)

                Column Status
0               Income   PASS
1              Recency   PASS
2                  Age   PASS
3       Total_spending   PASS
4       Total_Purchase   PASS
5          Family_size   PASS
6      NumWebPurchases   PASS
7    NumStorePurchases   PASS
8  NumCatalogPurchases   PASS

In [31]:
print(" MODEL VALIDATION")
print("=" * 60)

try:
    model = joblib.load(model_path)
    print(" K-Means model loaded successfully")
    print("Model type:", type(model).__name__)
except Exception as e:
    model = None
    print(" Model loading failed")
    print("Error:", e)

 MODEL VALIDATION
============================================================
 K-Means model loaded successfully
Model type: KMeans

In [32]:
print(" MODEL VALIDATION")
print("=" * 60)

try:
    model = joblib.load(model_path)
    print(" K-Means model loaded successfully")
    print("Model type:", type(model).__name__)
except Exception as e:
    model = None
    print(" Model loading failed")
    print("Error:", e)

 MODEL VALIDATION
============================================================
 K-Means model loaded successfully
Model type: KMeans

In [33]:
if model is not None:

    if hasattr(model, "n_features_in_"):
        print("Model expects:", model.n_features_in_, "features")
    else:
        print(" Model does not expose n_features_in_")

    if hasattr(model, "feature_names_in_"):
        print("Feature names detected:")
        print(list(model.feature_names_in_))

Model expects: 40 features
Feature names detected:
['Education', 'Marital_Status', 'Income', 'Recency', 'MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts', 'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth', 'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1', 'AcceptedCmp2', 'Complain', 'Response', 'Age', 'Year', 'Month', 'Day', 'Customer_Age', 'Customer_Tenure', 'Total_Children', 'Partner', 'Family_size', 'Total_spending', 'Total_Purchase', 'Total_Campaign', 'Average Spending per Purchase', 'Digital_Engagement', 'Deal_Dependency', 'Preferred_Shopping_Channel', 'Product_Preference', 'Customer_Activity_Level']

In [34]:
print("DAY 3 RESULTS VALIDATION")
print("=" * 60)

try:
    day3_results = joblib.load(results_path)

    print(" day3_results.pkl loaded")
    print("Saved items:")

    for key in day3_results.keys():
        print("Found", key)

except Exception as e:
    day3_results = None
    print("No Found Day 3 results loading failed")
    print("Error:", e)

DAY 3 RESULTS VALIDATION
============================================================
 day3_results.pkl loaded
Saved items:
Found predicted_cluster
Found customers_in_segment
Found activity_level
Found risk_level
Found preferred_channel
Found marketing_message
Found personalized_offer
Found campaign_timing
Found discount_strategy
Found retention_strategy
Found primary_product
Found secondary_product
Found cross_selling
Found upselling
Found segment_summary
Found marketing_recommendation
Found segment_customers

In [35]:

# Cell 13 CHECK AVAILABLE QA DATAFRAMES


print("Checking QA variables...")
print("=" * 60)

qa_dataframes = []

for name, value in list(globals().items()):
    if hasattr(value, "columns"):
        qa_dataframes.append(name)

for name in qa_dataframes:
    value = globals()[name]
    print(f"{name} -> {list(value.columns)}")

Checking QA variables...
============================================================
file_test_df -> ['Test', 'Status', 'Path']
df -> ['Education', 'Marital_Status', 'Income', 'Recency', 'MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts', 'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth', 'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1', 'AcceptedCmp2', 'Complain', 'Response', 'Age', 'Year', 'Month', 'Day', 'Customer_Age', 'Customer_Tenure', 'Total_Children', 'Partner', 'Family_size', 'Total_spending', 'Total_Purchase', 'Total_Campaign', 'Average Spending per Purchase', 'Digital_Engagement', 'Deal_Dependency', 'Preferred_Shopping_Channel', 'Product_Preference', 'Customer_Activity_Level', 'Cluster', 'Customer_Segment']
column_test_df -> ['Column', 'Status']
value -> ['Column', 'Status']
results_test_df -> ['Test', 'Status', 'Details']
qa_results_df -> ['Test', 'Status', 'Details']

In [36]:

# CELL 14 — QA RESULTS DATAFRAME


# Check which QA result dataframe is available

if "results_test_df" in globals():
    qa_df = results_test_df.copy()
elif "qa_results" in globals():
    qa_df = qa_results.copy()
elif "test_results" in globals():
    qa_df = test_results.copy()
else:
    qa_df = None

if qa_df is not None:
    print(" QA results dataframe found")
    print("Shape:", qa_df.shape)
    display(qa_df.head())
else:
    print(" No QA results dataframe found yet.")

 QA results dataframe found
Shape: (6, 3)

                   Test Status                   Details
0  Dataset Availability   PASS    Main dataframe checked
1     Dataset Not Empty   PASS                Rows: 2038
2       Duplicate Check   PASS             Duplicates: 0
3  Missing Values Check   PASS         Missing values: 0
4        Cluster Column   PASS  Cluster column available

In [37]:

# CELL 15 — CREATE QA RESULTS


import pandas as pd

# QA test results
qa_results = []

def add_test(test_name, condition, details=""):
    qa_results.append({
        "Test": test_name,
        "Status": "PASS" if condition else "FAIL",
        "Details": details
    })


# 1. Dataset exists
add_test(
    "Dataset Availability",
    "df" in globals() and isinstance(df, pd.DataFrame),
    "Main dataframe checked"
)


# 2. Dataset not empty
if "df" in globals() and isinstance(df, pd.DataFrame):
    add_test(
        "Dataset Not Empty",
        len(df) > 0,
        f"Rows: {len(df)}"
    )


# 3. Duplicate check
if "df" in globals() and isinstance(df, pd.DataFrame):
    duplicates = df.duplicated().sum()

    add_test(
        "Duplicate Check",
        duplicates == 0,
        f"Duplicates: {duplicates}"
    )


# 4. Missing values
if "df" in globals() and isinstance(df, pd.DataFrame):
    missing = df.isnull().sum().sum()

    add_test(
        "Missing Values Check",
        missing == 0,
        f"Missing values: {missing}"
    )


# 5. Cluster column
if "df" in globals() and isinstance(df, pd.DataFrame):
    cluster_exists = "Cluster" in df.columns

    add_test(
        "Cluster Column",
        cluster_exists,
        "Cluster column available"
    )


# 6. Model file
from pathlib import Path

model_paths = list(
    Path(r"D:\AI-Lab-99").rglob("kmeans_model.pkl")
)

add_test(
    "KMeans Model File",
    len(model_paths) > 0,
    str(model_paths[0]) if model_paths else "Model not found"
)


# Create dataframe
results_test_df = pd.DataFrame(qa_results)

# Also create compatible variable
qa_results_df = results_test_df.copy()

print(" QA RESULTS CREATED")
print("=" * 60)

display(results_test_df)

 QA RESULTS CREATED
============================================================

,Test,Status,Details
0,Dataset Availability,PASS,Main dataframe checked
1,Dataset Not Empty,PASS,Rows: 2038
2,Duplicate Check,PASS,Duplicates: 0
3,Missing Values Check,PASS,Missing values: 0
4,Cluster Column,PASS,Cluster column available
5,KMeans Model File,PASS,D:\AI-Lab-99\Week 4\Module 6 Customer Segmenta...

In [38]:

# CELL 16 — FINAL QA SUMMARY


total_tests = len(results_test_df)

passed_tests = (
    results_test_df["Status"] == "PASS"
).sum()

failed_tests = (
    results_test_df["Status"] == "FAIL"
).sum()

print(" FINAL QA SUMMARY")
print("=" * 60)

print("Total Tests :", total_tests)
print("Passed      :", passed_tests)
print("Failed      :", failed_tests)

if failed_tests == 0:
    print("\n ALL QA TESTS PASSED")
else:
    print("\n SOME QA TESTS FAILED — REVIEW REQUIRED")

 FINAL QA SUMMARY
============================================================
Total Tests : 6
Passed      : 6
Failed      : 0

 ALL QA TESTS PASSED

In [39]:

# CELL 17 — SAVE DAY 4 QA RESULTS


from pathlib import Path
import joblib

# Day 4 folder
day4_folder = Path(r"D:\AI-Lab-99\Week 5\Day 4")
day4_folder.mkdir(parents=True, exist_ok=True)

# Save QA dataframe
qa_file = day4_folder / "qa_results.pkl"

joblib.dump(results_test_df, qa_file)

print(" DAY 4 QA RESULTS SAVED")
print("=" * 60)
print("File:")
print(qa_file)
print()
print("Total Tests :", len(results_test_df))
print("Passed      :", (results_test_df["Status"] == "PASS").sum())
print("Failed      :", (results_test_df["Status"] == "FAIL").sum())

 DAY 4 QA RESULTS SAVED
============================================================
File:
D:\AI-Lab-99\Week 5\Day 4\qa_results.pkl

Total Tests : 6
Passed      : 6
Failed      : 0

In [40]:

# CELL 18 — FINAL QA REPORT


print(" DAY 4 — FINAL QUALITY ASSURANCE REPORT")
print("=" * 60)

print("QA Status       : PASSED ")
print("Total Tests     :", len(results_test_df))
print("Passed Tests    :", (results_test_df["Status"] == "PASS").sum())
print("Failed Tests    :", (results_test_df["Status"] == "FAIL").sum())
print("Pass Rate       : 100%")

print("\n TEST RESULTS")
print("-" * 60)

display(results_test_df)

 DAY 4 — FINAL QUALITY ASSURANCE REPORT
============================================================
QA Status       : PASSED
Total Tests     : 6
Passed Tests    : 6
Failed Tests    : 0
Pass Rate       : 100%

 TEST RESULTS
------------------------------------------------------------

,Test,Status,Details
0,Dataset Availability,PASS,Main dataframe checked
1,Dataset Not Empty,PASS,Rows: 2038
2,Duplicate Check,PASS,Duplicates: 0
3,Missing Values Check,PASS,Missing values: 0
4,Cluster Column,PASS,Cluster column available
5,KMeans Model File,PASS,D:\AI-Lab-99\Week 4\Module 6 Customer Segmenta...